import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import $ from './layout.module.scss';
import Themes from '@/components/Themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={$.main}>
          <Themes />
          {children}
        </main>
      </body>
    </html>
  );
}
